### ISSUE TITLE
Build keretrendszer + CI beüzemelése

### ISSUE THREAD

**Issue by ghost** [BME-MIT-IET/iet-hf2021-els-iet-ve#1]
Ki kéne találni, hogy működik a GitHub Actions, és ebben megbuildelni a projektet. Majd később a többi technikai fókuszú feladatot is érdemes lenne ide bekötni (Unit Test, NuGet...).

**Comment by nemethdani** [comment]
nagyon masic .net build action, unit testek lefutnak: #12 
sonarcloud-ba nem lehet bekötni. Alternatíva lehet egy saját sonarcloud server(de ez körülményes bme cloudban időlimitek miatt)
ehelyett jónak és hasonlónak tűnik a codacy, ha van rá igény, bekötöm
nuget is lessz hamarosan
