### ISSUE TITLE
Deployment segítése

### ISSUE THREAD

**Issue by ghost** [BME-MIT-IET/iet-hf2021-els-iet-ve#3]
Automatikusan NuGet csomagot csinálunk a projektból és azt feltöltjük valahova.

**Comment by Daaaaemon** [comment]
Van ehhez egy jól festő előre konfigurált action amit használhatnánk: https://github.com/brandedoutcast/publish-nuget

**Comment by nemethdani** [comment]
#16 vel azureba nuget deployment

**Comment by ghost** [comment]
Ez akkor a #17 után le van zárva, vagy még dolgozol rajta?

**Comment by nemethdani** [comment]
#17 lezárja, kész
